"use client";

import { useState } from "react";
import {
  TrendingUp,
  Download,
  CheckCircle2,
  FileDown,
  Sparkles,
  RefreshCw,
  XCircle,
  AlertTriangle,
  PlayCircle,
  HelpCircle,
} from "lucide-react";
import { toast } from "sonner";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

interface AbTestLaunchTabProps {
  abTestPlan: {
    hypothesis: string;
    variableTested: string;
    routeA: {
      name: string;
      angle: string;
      targetAudience: string;
      primaryMetric: string;
      targetBenchmark: string;
    };
    routeB: {
      name: string;
      angle: string;
      targetAudience: string;
      primaryMetric: string;
      targetBenchmark: string;
    };
    evaluationMetrics: Array<{
      metric: string;
      benchmark: string;
      purpose: string;
    }>;
    expectedLearning: string;
  };
  performanceLearning: {
    analyzedSource: string;
    keep: string[];
    change: string[];
    stop: string[];
    testNext: string[];
  };
  fullCampaignData: any;
  productName: string;
}

export const AbTestLaunchTab = ({
  abTestPlan,
  performanceLearning,
  fullCampaignData,
  productName,
}: AbTestLaunchTabProps) => {
  const [isExporting, setIsExporting] = useState(false);

  const handleExportMarkdown = () => {
    setIsExporting(true);
    const mdContent = `# COMMERCE LAUNCH PACK: ${productName.toUpperCase()}
Generated by BytePlus AI Suite (Seed 2.1, Seedream 5.0 Pro, Seedance 2.5, Audio 1.0)
Timestamp: ${new Date().toISOString()}

=======================================================
1. STRATEGIC POSITIONING & ANGLE
=======================================================
- Main Campaign Angle: "${fullCampaignData.positioning?.mainCampaignAngle}"
- Core Selling Message: "${fullCampaignData.positioning?.coreSellingMessage}"
- Demographics: ${fullCampaignData.positioning?.targetAudiencePersona?.demographics}
- Conversion Trigger: ${fullCampaignData.positioning?.targetAudiencePersona?.buyingTrigger}

=======================================================
2. A/B CREATIVE ROUTES
=======================================================
[ROUTE A]: ${fullCampaignData.creativeRoutes?.[0]?.name}
- Hook: ${fullCampaignData.creativeRoutes?.[0]?.hookIdea}
- Visual Direction: ${fullCampaignData.creativeRoutes?.[0]?.visualDirection}
- Ad Title: ${fullCampaignData.creativeRoutes?.[0]?.adCopy?.title}

[ROUTE B]: ${fullCampaignData.creativeRoutes?.[1]?.name}
- Hook: ${fullCampaignData.creativeRoutes?.[1]?.hookIdea}
- Visual Direction: ${fullCampaignData.creativeRoutes?.[1]?.visualDirection}
- Ad Title: ${fullCampaignData.creativeRoutes?.[1]?.adCopy?.title}

=======================================================
3. SHORT VIDEO SCRIPT (9:16 VERTICAL ADS)
=======================================================
Model: BytePlus Seedance 2.5 + Audio 1.0
${fullCampaignData.videoAsset?.scenes?.map((s: any) => `[Scene ${s.sceneNum} (${s.timing}) - ${s.title}]\n- Visual: ${s.visualPrompt}\n- Voiceover: "${s.voiceoverText}"\n- Text: ${s.onScreenText}`).join("\n\n")}

=======================================================
4. E-COMMERCE LISTING COPY
=======================================================
- SEO Title: ${fullCampaignData.commerceCopy?.seoTitle}

- 5 Key Bullet Points:
${fullCampaignData.commerceCopy?.bulletPoints?.map((b: string) => `  * ${b}`).join("\n")}

- Full Description:
${fullCampaignData.commerceCopy?.productDescription}

=======================================================
5. A/B TESTING & PERFORMANCE LEARNING
=======================================================
- Hypothesis: ${abTestPlan.hypothesis}
- Variable: ${abTestPlan.variableTested}
- Expected Learning: ${abTestPlan.expectedLearning}
- Keep: ${performanceLearning.keep?.join(" | ")}
- Change: ${performanceLearning.change?.join(" | ")}
- Stop: ${performanceLearning.stop?.join(" | ")}
- Test Next: ${performanceLearning.testNext?.join(" | ")}
`;

    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Launch_Pack_${productName.replace(/\s+/g, "_")}.md`;
    link.click();
    URL.revokeObjectURL(url);
    setIsExporting(false);
    toast.success("Launch Pack (.md) exported successfully.");
  };

  const handleExportJSON = () => {
    const jsonStr = JSON.stringify(fullCampaignData, null, 2);
    const blob = new Blob([jsonStr], { type: "application/json;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Campaign_Data_${productName.replace(/\s+/g, "_")}.json`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success("Campaign JSON exported successfully.");
  };

  return (
    <div className="space-y-4">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-900 text-white p-4 rounded-lg shadow-2xs">
        <div className="space-y-0.5">
          <div className="flex items-center gap-2">
            <Badge className="bg-teal-500/20 text-teal-300 border-teal-400/30 text-[10px] font-bold">
              AI Performance Feedback Loop
            </Badge>
            <Badge className="bg-white/10 text-slate-300 text-[10px] font-medium">
              1-Click Deployment
            </Badge>
          </div>
          <h2 className="text-base font-bold tracking-tight">
            A/B Testing Plan &amp; Performance Learning Pack
          </h2>
          <p className="text-xs text-slate-400">
            Automated optimization feedback derived from historical benchmarks (Keep / Change / Stop / Test Next) with one-click export for media buyers.
          </p>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <Button
            size="sm"
            onClick={handleExportMarkdown}
            disabled={isExporting}
            className="bg-teal-600 hover:bg-teal-700 text-white text-xs font-bold h-8 px-3 shadow-2xs"
          >
            <FileDown className="mr-1.5 size-3.5" /> 1-Click Launch Pack (.MD)
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={handleExportJSON}
            className="bg-white/10 border-white/20 text-white hover:bg-white/20 text-xs font-bold h-8 px-3"
          >
            <Download className="mr-1.5 size-3.5" /> JSON Pack
          </Button>
        </div>
      </div>

      {/* A/B Testing Execution Plan */}
      <Card className="border-slate-300 shadow-2xs rounded-lg bg-white">
        <CardHeader className="py-2.5 px-4 border-b bg-slate-50">
          <CardTitle className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
            <TrendingUp className="size-3.5 text-teal-600" />
            Structured A/B Testing Execution Framework
          </CardTitle>
        </CardHeader>
        <CardContent className="p-4 space-y-3.5 text-xs">
          <div className="space-y-1">
            <span className="font-bold text-slate-500 uppercase text-[10px] tracking-wider block">
              Core Test Hypothesis:
            </span>
            <p className="text-slate-900 bg-slate-50 p-3 rounded border border-slate-200 font-semibold leading-relaxed">
              {abTestPlan.hypothesis}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
            {/* Route A Spec */}
            <div className="bg-slate-50 p-3.5 rounded border border-slate-200 space-y-1.5">
              <div className="flex items-center justify-between">
                <Badge className="bg-indigo-600 text-white font-bold text-[10px]">ROUTE A</Badge>
                <span className="text-[10px] text-slate-500 font-mono">50% Budget</span>
              </div>
              <h4 className="font-bold text-slate-900 text-xs">{abTestPlan.routeA.name}</h4>
              <p className="text-slate-700"><strong>Angle:</strong> {abTestPlan.routeA.angle}</p>
              <p className="text-slate-700"><strong>Primary KPI:</strong> {abTestPlan.routeA.primaryMetric}</p>
              <p className="text-emerald-700 font-semibold"><strong>Target:</strong> {abTestPlan.routeA.targetBenchmark}</p>
            </div>

            {/* Route B Spec */}
            <div className="bg-slate-50 p-3.5 rounded border border-slate-200 space-y-1.5">
              <div className="flex items-center justify-between">
                <Badge className="bg-purple-600 text-white font-bold text-[10px]">ROUTE B</Badge>
                <span className="text-[10px] text-slate-500 font-mono">50% Budget</span>
              </div>
              <h4 className="font-bold text-slate-900 text-xs">{abTestPlan.routeB.name}</h4>
              <p className="text-slate-700"><strong>Angle:</strong> {abTestPlan.routeB.angle}</p>
              <p className="text-slate-700"><strong>Primary KPI:</strong> {abTestPlan.routeB.primaryMetric}</p>
              <p className="text-purple-700 font-semibold"><strong>Target:</strong> {abTestPlan.routeB.targetBenchmark}</p>
            </div>
          </div>

          {/* KPI Target Table */}
          <div className="space-y-1.5 pt-2 border-t border-slate-100">
            <span className="font-bold text-slate-500 uppercase text-[10px] tracking-wider block">
              Evaluation Metrics &amp; Gate Benchmarks:
            </span>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {abTestPlan.evaluationMetrics.map((kpi, idx) => (
                <div key={idx} className="bg-white p-2.5 rounded border border-slate-200 shadow-2xs space-y-0.5">
                  <span className="text-[10px] text-slate-500 font-medium block truncate">{kpi.metric}</span>
                  <p className="text-xs font-extrabold text-slate-900">{kpi.benchmark}</p>
                  <span className="text-[10px] text-slate-400 block truncate">{kpi.purpose}</span>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Performance Learning Matrix (Keep, Change, Stop, Test Next) */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <h3 className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
            <Sparkles className="size-3.5 text-yellow-500" />
            Continuous Performance Feedback (Keep / Change / Stop / Test Next)
          </h3>
          <span className="text-[11px] text-slate-500">
            Source: {performanceLearning.analyzedSource}
          </span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {/* KEEP */}
          <Card className="border-slate-300 shadow-2xs rounded-lg bg-white">
            <CardHeader className="py-2 px-3 border-b bg-emerald-50">
              <CardTitle className="text-xs font-bold text-emerald-900 flex items-center gap-1">
                <CheckCircle2 className="size-3.5 text-emerald-600" />
                KEEP (High Performer)
              </CardTitle>
            </CardHeader>
            <CardContent className="p-3 space-y-2 text-xs">
              {performanceLearning.keep.map((item, idx) => (
                <div key={idx} className="p-2 rounded bg-emerald-50/50 border border-emerald-100 text-slate-800 leading-relaxed font-medium">
                  {item}
                </div>
              ))}
            </CardContent>
          </Card>

          {/* CHANGE */}
          <Card className="border-slate-300 shadow-2xs rounded-lg bg-white">
            <CardHeader className="py-2 px-3 border-b bg-amber-50">
              <CardTitle className="text-xs font-bold text-amber-900 flex items-center gap-1">
                <RefreshCw className="size-3.5 text-amber-600" />
                CHANGE (Refinement)
              </CardTitle>
            </CardHeader>
            <CardContent className="p-3 space-y-2 text-xs">
              {performanceLearning.change.map((item, idx) => (
                <div key={idx} className="p-2 rounded bg-amber-50/50 border border-amber-100 text-slate-800 leading-relaxed font-medium">
                  {item}
                </div>
              ))}
            </CardContent>
          </Card>

          {/* STOP */}
          <Card className="border-slate-300 shadow-2xs rounded-lg bg-white">
            <CardHeader className="py-2 px-3 border-b bg-rose-50">
              <CardTitle className="text-xs font-bold text-rose-900 flex items-center gap-1">
                <XCircle className="size-3.5 text-rose-600" />
                STOP (Low ROI Waste)
              </CardTitle>
            </CardHeader>
            <CardContent className="p-3 space-y-2 text-xs">
              {performanceLearning.stop.map((item, idx) => (
                <div key={idx} className="p-2 rounded bg-rose-50/50 border border-rose-100 text-slate-800 leading-relaxed font-medium">
                  {item}
                </div>
              ))}
            </CardContent>
          </Card>

          {/* TEST NEXT */}
          <Card className="border-slate-300 shadow-2xs rounded-lg bg-white">
            <CardHeader className="py-2 px-3 border-b bg-indigo-50">
              <CardTitle className="text-xs font-bold text-indigo-900 flex items-center gap-1">
                <PlayCircle className="size-3.5 text-indigo-600" />
                TEST NEXT (Iterative Scale)
              </CardTitle>
            </CardHeader>
            <CardContent className="p-3 space-y-2 text-xs">
              {performanceLearning.testNext.map((item, idx) => (
                <div key={idx} className="p-2 rounded bg-indigo-50/50 border border-indigo-100 text-slate-800 leading-relaxed font-medium">
                  {item}
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};
