"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  Download,
  Edit2,
  CheckCircle2,
} from "lucide-react";
import { toast } from "sonner";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

interface ImageAssetsTabProps {
  imageAssets: Array<{
    id: string;
    type: string;
    title: string;
    aspectRatio: string;
    recommendedFormat: string;
    imageUrl: string;
    modelUsed: string;
    promptUsed: string;
    usage: string;
  }>;
  projectId: string;
  productName: string;
}

export const ImageAssetsTab = ({ imageAssets, projectId, productName }: ImageAssetsTabProps) => {
  const router = useRouter();

  const handleDownloadAll = () => {
    toast.success("Downloading all HD e-commerce product visuals...");
    imageAssets.forEach((asset, idx) => {
      setTimeout(() => {
        const link = document.createElement("a");
        link.href = asset.imageUrl;
        link.download = `${productName.replace(/\s+/g, "_")}_${asset.type}.jpg`;
        link.target = "_blank";
        link.click();
      }, idx * 250);
    });
  };

  return (
    <div className="space-y-4">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-900 text-white p-4 rounded-lg shadow-2xs">
        <div className="space-y-0.5">
          <div className="flex items-center gap-2">
            <Badge className="bg-emerald-500/20 text-emerald-300 border-emerald-400/30 text-[10px] font-bold">
              BytePlus Seedream 5.0 Pro
            </Badge>
            <Badge className="bg-white/10 text-slate-300 text-[10px] font-medium">
              4 E-Commerce Standard Formats
            </Badge>
          </div>
          <h2 className="text-base font-bold tracking-tight">
            E-Commerce Visual Asset Collection
          </h2>
          <p className="text-xs text-slate-400">
            High-fidelity visuals generated by Seedream 5.0 Pro with brand consistency preservation for marketplace listings and ad creatives.
          </p>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <Button
            size="sm"
            onClick={handleDownloadAll}
            className="bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold h-8 px-3 shadow-2xs"
          >
            <Download className="mr-1.5 size-3.5" /> Download All 4 HD Images
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => router.push(`/editor/${projectId}`)}
            className="bg-white/10 border-white/20 text-white hover:bg-white/20 text-xs font-bold h-8 px-3"
          >
            <Edit2 className="mr-1.5 size-3.5 text-emerald-400" /> Open Graphic Canvas
          </Button>
        </div>
      </div>

      {/* 4 Images Matrix Grid (2x2) */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {imageAssets.map((asset, idx) => (
          <Card
            key={asset.id || idx}
            className="border-slate-300 shadow-2xs rounded-lg overflow-hidden bg-white flex flex-col justify-between"
          >
            <div>
              <CardHeader className="bg-slate-50 border-b py-2.5 px-4 flex flex-row items-center justify-between">
                <div className="space-y-0.5">
                  <div className="flex items-center gap-1.5">
                    <Badge className="bg-slate-900 text-white text-[10px] font-bold">
                      {asset.type}
                    </Badge>
                    <Badge variant="outline" className="text-[10px] font-semibold text-emerald-700 bg-emerald-50 border-emerald-200">
                      {asset.aspectRatio} ({asset.recommendedFormat})
                    </Badge>
                  </div>
                  <CardTitle className="text-xs font-bold text-slate-900 pt-0.5">
                    {asset.title}
                  </CardTitle>
                </div>

                <Badge variant="secondary" className="text-[10px] text-slate-500 font-mono">
                  {asset.modelUsed}
                </Badge>
              </CardHeader>

              {/* Image Preview Container */}
              <div className="p-3 bg-slate-50 flex items-center justify-center relative group min-h-[260px]">
                <img
                  src={asset.imageUrl}
                  alt={asset.title}
                  className="rounded-md shadow-2xs max-h-[280px] w-auto object-cover border border-slate-200"
                />

                {/* Hover Overlay */}
                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2 rounded-md m-3 backdrop-blur-2xs">
                  <a href={asset.imageUrl} target="_blank" rel="noreferrer" download>
                    <Button size="sm" className="bg-white text-slate-900 hover:bg-slate-100 text-xs font-bold h-7 px-3">
                      <Download className="mr-1 size-3" /> Download HD
                    </Button>
                  </a>
                  <Button
                    size="sm"
                    className="bg-indigo-600 text-white hover:bg-indigo-700 text-xs font-bold h-7 px-3"
                    onClick={() => router.push(`/editor/${projectId}`)}
                  >
                    <Edit2 className="mr-1 size-3" /> Canvas Studio
                  </Button>
                </div>
              </div>

              {/* Prompt & Usage Meta */}
              <CardContent className="p-4 space-y-2 text-xs">
                <div className="space-y-0.5">
                  <span className="font-bold text-slate-500 uppercase text-[10px] tracking-wider block">
                    Marketplace Placement:
                  </span>
                  <p className="text-slate-800 font-medium leading-relaxed bg-slate-50 p-2 rounded border border-slate-200">
                    {asset.usage}
                  </p>
                </div>

                <div className="space-y-0.5">
                  <span className="font-bold text-slate-500 uppercase text-[10px] tracking-wider block">
                    Optimized Seedream 5.0 Pro Prompt:
                  </span>
                  <p className="text-slate-600 font-mono text-[10px] bg-slate-50 p-2 rounded border border-slate-200 leading-relaxed">
                    {asset.promptUsed}
                  </p>
                </div>
              </CardContent>
            </div>

            {/* Card Footer Actions */}
            <div className="p-3 border-t bg-slate-50 flex items-center justify-between text-xs">
              <span className="text-[11px] text-emerald-700 font-semibold flex items-center gap-1">
                <CheckCircle2 className="size-3.5 text-emerald-600" /> Marketplace Ready
              </span>

              <div className="flex items-center gap-1.5">
                <a href={asset.imageUrl} target="_blank" rel="noreferrer" download>
                  <Button size="sm" variant="outline" className="h-7 text-xs border-slate-300">
                    <Download className="mr-1 size-3" /> Download
                  </Button>
                </a>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => router.push(`/editor/${projectId}`)}
                  className="h-7 text-xs border-indigo-200 text-indigo-700 hover:bg-indigo-50 font-semibold"
                >
                  <Edit2 className="mr-1 size-3" /> Canvas Studio
                </Button>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
};
