"use client";

import { useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Palette, Plus } from "lucide-react";
import { toast } from "sonner";
import { getMockProduct } from "@/features/campaign/mock-data";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const productTabs = ["General", "Brand & claims", "Source assets", "Audience & market"];
export default function ProductDetailPage() { const { productId } = useParams<{ productId: string }>(); const router = useRouter(); const product = useMemo(() => getMockProduct(productId), [productId]); const [title, setTitle] = useState(product.name); const [dataTab, setDataTab] = useState("General"); const [assets, setAssets] = useState(product.assets);
  return <div className="mx-auto max-w-7xl space-y-5 pb-12"><div className="flex items-center justify-between"><Button variant="ghost" size="sm" onClick={() => router.push("/content-ai")}><ArrowLeft className="mr-1.5 size-4" />All products</Button><Button onClick={() => toast.success("Product saved.")}>Update product</Button></div><div><p className="text-xs text-slate-500">Product / {product.sku}</p><h1 className="text-xl font-bold">{title}</h1></div><ProductInfo title={title} setTitle={setTitle} product={product} assets={assets} setAssets={setAssets} dataTab={dataTab} setDataTab={setDataTab} /></div>; }
function ProductInfo({ title, setTitle, product, assets, setAssets, dataTab, setDataTab }: { title: string; setTitle: (value: string) => void; product: ReturnType<typeof getMockProduct>; assets: ReturnType<typeof getMockProduct>["assets"]; setAssets: (assets: ReturnType<typeof getMockProduct>["assets"]) => void; dataTab: string; setDataTab: (tab: string) => void }) { return <div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div className="space-y-5"><Input value={title} onChange={(e) => setTitle(e.target.value)} className="h-12 text-xl font-semibold" aria-label="Product name" /><p className="-mt-3 text-xs text-slate-500">Permalink: <span className="text-indigo-600">/product/{product.sku.toLowerCase()}</span> · Edit</p><Card><CardHeader className="border-b bg-slate-50 py-3"><CardTitle className="text-sm">Product description</CardTitle></CardHeader><CardContent className="p-0"><Textarea defaultValue={`${product.usp}\n\nUse this area for a detailed product description, shopper FAQs and trust-building details.`} className="min-h-[180px] resize-y rounded-none border-0 p-4 text-sm focus-visible:ring-0" /></CardContent></Card><Card><CardHeader className="border-b bg-slate-50 py-3"><CardTitle className="text-sm">Product data</CardTitle></CardHeader><CardContent className="grid p-0 md:grid-cols-[190px_1fr]"><div className="border-b bg-slate-50/60 p-2 md:border-b-0 md:border-r">{productTabs.map((tab) => <button key={tab} onClick={() => setDataTab(tab)} className={`flex w-full items-center rounded-md px-3 py-2 text-left text-sm ${dataTab === tab ? "bg-white font-semibold text-indigo-700 shadow-sm" : "text-slate-600 hover:bg-white"}`}>{tab}</button>)}</div><div className="p-5"><ProductData active={dataTab} product={product} assets={assets} setAssets={setAssets} /></div></CardContent></Card><Card><CardHeader className="border-b bg-slate-50 py-3"><CardTitle className="text-sm">Product short description</CardTitle></CardHeader><CardContent><Textarea defaultValue="A concise storefront summary that introduces the product benefit and makes the promotion easy to scan." rows={4} className="text-sm" /></CardContent></Card></div><PublishSidebar product={product} assets={assets} setAssets={setAssets} /></div>; }
function ProductData({ active, product, assets, setAssets }: { active: string; product: ReturnType<typeof getMockProduct>; assets: ReturnType<typeof getMockProduct>["assets"]; setAssets: (assets: ReturnType<typeof getMockProduct>["assets"]) => void }) { if (active === "General") return <div className="space-y-4"><FormRow label="Regular price ($)"><Input defaultValue={product.price.replace("$", "")} /></FormRow><FormRow label="Sale price ($)"><Input defaultValue="26.90" /></FormRow><FormRow label="Promotion"><Input defaultValue={product.promotion} /></FormRow><FormRow label="Tax status"><select className="h-10 w-full rounded-md border bg-white px-3 text-sm"><option>Taxable</option><option>Shipping only</option><option>None</option></select></FormRow></div>; if (active === "Brand & claims") return <div className="space-y-5"><div className="flex items-center gap-2"><Palette className="size-4 text-indigo-600" /><div><p className="font-semibold">{product.brand.name}</p><p className="text-xs text-slate-500">{product.brand.tone}</p></div></div><div className="flex gap-2">{product.brand.colors.map((color) => <span key={color} className="size-9 rounded-full border" style={{ backgroundColor: color }} />)}</div><div className="grid gap-3 md:grid-cols-2"><ClaimBox title="Allowed claims" claims={product.requiredClaims} tone="emerald" /><ClaimBox title="Restricted wording" claims={product.restrictedClaims} tone="rose" /></div></div>; if (active === "Source assets") return <div className="space-y-4"><div className="flex items-center justify-between"><div><p className="font-semibold">Source asset library</p><p className="text-xs text-slate-500">References passed into image and video generation.</p></div><Button size="sm" variant="outline" onClick={() => { setAssets([...assets, { id: `asset-${Date.now()}`, name: "New source asset", url: product.image, role: "Hero", status: "needs-review" }]); toast.success("Mock source asset added."); }}><Plus className="mr-1 size-3.5" />Add asset</Button></div><div className="grid grid-cols-2 gap-3">{assets.map((asset) => <div key={asset.id} className="overflow-hidden rounded-lg border"><img src={asset.url} alt="" className="aspect-square w-full object-cover" /><div className="p-2"><p className="truncate text-xs font-semibold">{asset.name}</p><p className="mt-1 text-[11px] text-slate-500">{asset.role} · {asset.status}</p></div></div>)}</div></div>; return <div className="space-y-4"><FormRow label="Primary audience"><Textarea defaultValue={product.audience} /></FormRow><FormRow label="Target market"><Input defaultValue={product.market} /></FormRow><FormRow label="Recommended platforms"><Input defaultValue="TikTok Shop, Instagram Reels, Meta Feed" /></FormRow><FormRow label="Audience pain point"><Textarea defaultValue="Needs a credible, lightweight routine that feels easy to maintain." /></FormRow></div>; }
function PublishSidebar({ product, assets, setAssets }: { product: ReturnType<typeof getMockProduct>; assets: ReturnType<typeof getMockProduct>["assets"]; setAssets: (assets: ReturnType<typeof getMockProduct>["assets"]) => void }) { return <aside className="space-y-5"><Card><CardHeader className="border-b bg-slate-50 py-3"><CardTitle className="text-sm">Publish</CardTitle></CardHeader><CardContent className="space-y-3 p-4 text-sm"><p><span className="text-slate-500">Status:</span> Draft <button className="ml-1 text-indigo-600">Edit</button></p><p><span className="text-slate-500">Visibility:</span> Public <button className="ml-1 text-indigo-600">Edit</button></p><p><span className="text-slate-500">Publish:</span> Immediately <button className="ml-1 text-indigo-600">Edit</button></p><div className="flex items-center justify-between border-t pt-3"><button className="text-xs text-rose-600">Move to trash</button><Button size="sm" onClick={() => toast.success("Product updated.")}>Update</Button></div></CardContent></Card><Card><CardHeader className="border-b bg-slate-50 py-3"><CardTitle className="text-sm">Product categories</CardTitle></CardHeader><CardContent className="space-y-2 p-4 text-sm">{[product.category, "Featured launch"].map((category) => <label className="flex items-center gap-2" key={category}><input type="checkbox" defaultChecked />{category}</label>)}<button className="text-xs text-indigo-600">+ Add new category</button></CardContent></Card><Card><CardHeader className="border-b bg-slate-50 py-3"><CardTitle className="text-sm">Product image</CardTitle></CardHeader><CardContent className="p-4"><img src={product.image} alt="" className="aspect-square w-full rounded-lg object-cover" /><button className="mt-2 text-xs text-indigo-600">Replace product image</button></CardContent></Card><Card><CardHeader className="border-b bg-slate-50 py-3"><CardTitle className="text-sm">Product gallery</CardTitle></CardHeader><CardContent className="grid grid-cols-3 gap-2 p-4">{assets.slice(0, 3).map((asset) => <img key={asset.id} src={asset.url} alt="" className="aspect-square rounded object-cover" />)}<button onClick={() => { setAssets([...assets, { id: `asset-${Date.now()}`, name: "New gallery source", url: product.image, role: "Hero", status: "needs-review" }]); toast.success("Mock gallery asset added."); }} className="aspect-square rounded border border-dashed text-slate-400 hover:border-indigo-400 hover:text-indigo-600"><Plus className="mx-auto size-4" /></button></CardContent></Card></aside>; }
function ClaimBox({ title, claims, tone }: { title: string; claims: string[]; tone: "emerald" | "rose" }) { const className = tone === "emerald" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-rose-200 bg-rose-50 text-rose-800"; return <div className={`rounded-lg border p-3 ${className}`}><p className="text-xs font-bold">{title}</p><div className="mt-2 flex flex-wrap gap-1">{claims.map((claim) => <Badge key={claim} className="bg-white text-slate-700 hover:bg-white">{claim}</Badge>)}</div></div>; }
function FormRow({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2 md:grid-cols-[150px_1fr]"><Label className="pt-2 text-sm text-slate-600">{label}</Label>{children}</div>; }
