"use client";

import { fabric } from "fabric";
import { FlipHorizontal2, FlipVertical2, RotateCw, Save, Type, Undo2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

type Props = { open: boolean; imageUrl: string; imageName: string; onOpenChange: (open: boolean) => void; onSave: (blob: Blob, width: number, height: number) => Promise<void> };
const sizes = { "1:1": [560, 560], "4:5": [448, 560], "16:9": [720, 405] } as const;

export function MediaImageEditor({ open, imageUrl, imageName, onOpenChange, onSave }: Props) {
  const canvasElement = useRef<HTMLCanvasElement>(null); const canvas = useRef<fabric.Canvas | null>(null); const image = useRef<fabric.Image | null>(null);
  const [aspect, setAspect] = useState<keyof typeof sizes>("1:1"); const [text, setText] = useState("Shop now"); const [saving, setSaving] = useState(false); const [revision, setRevision] = useState(0);
  useEffect(() => { if (!open || !canvasElement.current) return; const [width, height] = sizes[aspect]; const instance = new fabric.Canvas(canvasElement.current, { width, height, backgroundColor: "#f8fafc", preserveObjectStacking: true }); canvas.current = instance;
    fabric.Image.fromURL(imageUrl, (asset) => { const scale = Math.max(width / (asset.width || width), height / (asset.height || height)); asset.set({ left: width / 2, top: height / 2, originX: "center", originY: "center", scaleX: scale, scaleY: scale }); image.current = asset; instance.add(asset); instance.setActiveObject(asset); instance.renderAll(); }, { crossOrigin: "anonymous" });
    return () => { instance.dispose(); canvas.current = null; image.current = null; }; }, [open, imageUrl, aspect, revision]);
  const rotate = () => { if (!image.current) return; image.current.rotate((image.current.angle || 0) + 90); canvas.current?.renderAll(); };
  const flip = (axis: "x" | "y") => { if (!image.current) return; axis === "x" ? image.current.set("flipX", !image.current.flipX) : image.current.set("flipY", !image.current.flipY); canvas.current?.renderAll(); };
  const addText = () => { if (!canvas.current || !text.trim()) return; const value = new fabric.Textbox(text.trim(), { left: 80, top: 80, width: 300, fontFamily: "Arial", fontWeight: 700, fontSize: 42, fill: "#fff", stroke: "rgba(0,0,0,.35)", strokeWidth: 1 }); canvas.current.add(value); canvas.current.setActiveObject(value); };
  const filter = (kind: "none" | "grayscale" | "warm" | "contrast") => { if (!image.current) return; const filters = fabric.Image.filters; image.current.filters = kind === "grayscale" ? [new filters.Grayscale()] : kind === "warm" ? [new filters.Sepia()] : kind === "contrast" ? [new filters.Contrast({ contrast: 0.18 })] : []; image.current.applyFilters(); canvas.current?.renderAll(); };
  const reset = () => { setAspect("1:1"); setRevision((value) => value + 1); };
  const save = async () => { if (!canvas.current) return; setSaving(true); try { canvas.current.discardActiveObject(); canvas.current.renderAll(); const dataUrl = canvas.current.toDataURL({ format: "png", quality: 1, multiplier: 1 }); const blob = await (await fetch(dataUrl)).blob(); await onSave(blob, canvas.current.getWidth(), canvas.current.getHeight()); onOpenChange(false); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[94vh] max-w-6xl overflow-y-auto p-0"><DialogHeader className="border-b px-6 py-4"><DialogTitle>Edit image</DialogTitle><DialogDescription>{imageName} · Drag the image to reframe the crop, then add text or a filter.</DialogDescription></DialogHeader><div className="grid lg:grid-cols-[230px_1fr]"><aside className="space-y-5 border-r bg-slate-50 p-4"><Tool label="Crop ratio"><div className="grid grid-cols-3 gap-1">{(Object.keys(sizes) as (keyof typeof sizes)[]).map((value) => <Button key={value} size="sm" variant={aspect === value ? "default" : "outline"} onClick={() => setAspect(value)}>{value}</Button>)}</div></Tool><Tool label="Transform"><div className="grid grid-cols-3 gap-1"><Button size="icon" variant="outline" onClick={rotate}><RotateCw className="size-4" /></Button><Button size="icon" variant="outline" onClick={() => flip("x")}><FlipHorizontal2 className="size-4" /></Button><Button size="icon" variant="outline" onClick={() => flip("y")}><FlipVertical2 className="size-4" /></Button></div></Tool><Tool label="Text overlay"><Input value={text} onChange={(event) => setText(event.target.value)} /><Button className="mt-2 w-full" variant="outline" onClick={addText}><Type className="mr-2 size-4" />Add text</Button></Tool><Tool label="Filters"><div className="grid grid-cols-2 gap-1">{(["none", "grayscale", "warm", "contrast"] as const).map((value) => <Button key={value} size="sm" variant="outline" className="capitalize" onClick={() => filter(value)}>{value}</Button>)}</div></Tool><div className="flex gap-2 pt-3"><Button variant="ghost" size="sm" onClick={reset}><Undo2 className="mr-1 size-4" />Reset</Button><Button size="sm" className="flex-1" disabled={saving} onClick={save}><Save className="mr-1 size-4" />{saving ? "Saving…" : "Save version"}</Button></div></aside><main className="flex min-h-[620px] items-center justify-center overflow-auto bg-slate-900 p-6"><div className="overflow-hidden rounded shadow-2xl"><canvas ref={canvasElement} /></div></main></div></DialogContent></Dialog>;
}
function Tool({ label, children }: { label: string; children: React.ReactNode }) { return <div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p>{children}</div>; }
