"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Archive, CheckSquare2, Download, FileSpreadsheet, Plus, Rocket, Search, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import * as XLSX from "xlsx";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { mockProducts } from "@/features/campaign/mock-data";

export type CatalogProduct = { id: string; name: string; sku: string; category: string; brand: string; imageUrl: string; priceCents: number; currency: string; promotion: string; description: string; sellingPoints: string[]; requiredClaims: string[]; restrictedClaims: string[]; audience: string; targetMarket: string; status: "draft" | "active" | "archived"; readiness: number; createdAt?: string; updatedAt?: string };
const demoProducts: CatalogProduct[] = mockProducts.map((item) => ({ id: item.id, name: item.name, sku: item.sku, category: item.category, brand: item.brand.name, imageUrl: item.image, priceCents: Math.round(Number(item.price.replace(/[^0-9.]/g, "")) * 100), currency: "USD", promotion: item.promotion, description: item.usp, sellingPoints: [item.usp], requiredClaims: item.requiredClaims, restrictedClaims: item.restrictedClaims, audience: item.audience, targetMarket: item.market, status: item.readiness >= 80 ? "active" : "draft", readiness: item.readiness }));
const emptyProduct: CatalogProduct = { id: "", name: "", sku: "", category: "Uncategorized", brand: "", imageUrl: "", priceCents: 0, currency: "USD", promotion: "", description: "", sellingPoints: [], requiredClaims: [], restrictedClaims: [], audience: "", targetMarket: "Vietnam", status: "draft", readiness: 20 };

export function ProductCatalog() {
  const router = useRouter(); const searchParams = useSearchParams(); const fileRef = useRef<HTMLInputElement>(null);
  const [products, setProducts] = useState<CatalogProduct[]>(demoProducts); const [demoMode, setDemoMode] = useState(true); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [selected, setSelected] = useState<Set<string>>(new Set()); const [editorOpen, setEditorOpen] = useState(searchParams.get("action") === "new"); const [sheetOpen, setSheetOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [draft, setDraft] = useState<CatalogProduct>(emptyProduct); const [sheetRows, setSheetRows] = useState<CatalogProduct[]>([]); const [importRows, setImportRows] = useState<CatalogProduct[]>([]); const [importErrors, setImportErrors] = useState<string[]>([]); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/products?status=all&sort=newest").then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then((payload) => { setProducts(payload.data); setDemoMode(false); }).catch(() => { const saved = localStorage.getItem("commerce-demo-products"); if (saved) { try { setProducts(JSON.parse(saved)); } catch {} } setDemoMode(true); }); }, []);
  useEffect(() => { if (searchParams.get("action") === "new") { setDraft({ ...emptyProduct, sku: `NEW-${String(products.length + 1).padStart(3, "0")}` }); setEditorOpen(true); } }, [searchParams, products.length]);
  useEffect(() => { if (demoMode) localStorage.setItem("commerce-demo-products", JSON.stringify(products)); }, [products, demoMode]);
  const filtered = useMemo(() => products.filter((item) => (status === "all" || item.status === status) && `${item.name} ${item.sku} ${item.category} ${item.brand}`.toLowerCase().includes(query.toLowerCase())), [products, query, status]);
  const openNew = () => { setDraft({ ...emptyProduct, sku: `NEW-${String(products.length + 1).padStart(3, "0")}` }); setEditorOpen(true); };
  const saveProduct = async () => { if (!draft.name.trim() || !draft.sku.trim()) return toast.error("Product name and SKU are required."); setSaving(true); try { if (demoMode) { const value = { ...draft, id: draft.id || `demo-${crypto.randomUUID()}` }; setProducts((current) => draft.id ? current.map((item) => item.id === draft.id ? value : item) : [value, ...current]); } else { const response = await fetch(draft.id ? `/api/products/${draft.id}` : "/api/products", { method: draft.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); if (!response.ok) { const payload = await response.json(); throw new Error(payload.error || "Save failed"); } const value = (await response.json()).data; setProducts((current) => draft.id ? current.map((item) => item.id === value.id ? value : item) : [value, ...current]); } setEditorOpen(false); router.push("/content-ai?tab=products"); toast.success(draft.id ? "Product updated." : "Product created."); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save product."); } finally { setSaving(false); } };
  const createCampaign = async (product: CatalogProduct) => { if (demoMode || product.id.startsWith("mock-") || product.id.startsWith("demo-")) { router.push(`/workspace/demo-${product.id}`); toast.success("Demo campaign project created from this product."); return; } const response = await fetch(`/api/products/${product.id}/campaign`, { method: "POST" }); if (!response.ok) return toast.error("Could not create campaign project."); const payload = await response.json(); router.push(`/workspace/${payload.data.projectId}`); };
  const bulk = async (action: "archive" | "activate" | "trash") => { const ids = Array.from(selected); if (!ids.length) return; if (action === "trash" && !confirm(`Move ${ids.length} products to trash?`)) return; if (!demoMode) await fetch("/api/products/bulk", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids, action }) }); setProducts((current) => action === "trash" ? current.filter((item) => !ids.includes(item.id)) : current.map((item) => ids.includes(item.id) ? { ...item, status: action === "archive" ? "archived" : "active" } : item)); setSelected(new Set()); toast.success("Bulk action completed."); };
  const openSheet = () => { setSheetRows(products.map((item) => ({ ...item }))); setSheetOpen(true); };
  const saveSheet = async () => { const invalid = sheetRows.filter((row) => !row.name.trim() || !row.sku.trim()); if (invalid.length) return toast.error(`${invalid.length} rows need a product name and SKU.`); setSaving(true); try { if (!demoMode) { const response = await fetch("/api/products/bulk-upsert", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "update", rows: sheetRows }) }); if (!response.ok) throw new Error(); } setProducts(sheetRows); setSheetOpen(false); toast.success(`${sheetRows.length} product rows saved.`); } catch { toast.error("Spreadsheet changes could not be saved."); } finally { setSaving(false); } };
  const parseImport = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { const book = XLSX.read(await file.arrayBuffer()); const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(book.Sheets[book.SheetNames[0]], { defval: "" }); const parsed = rows.map((row, index) => fromImportRow(row, index)); const errors = parsed.flatMap((row, index) => [!row.name ? `Row ${index + 2}: product name is missing` : "", !row.sku ? `Row ${index + 2}: SKU is missing` : ""].filter(Boolean)); setImportRows(parsed); setImportErrors(errors); setImportOpen(true); } catch { toast.error("The CSV/XLSX file could not be read."); } event.target.value = ""; };
  const commitImport = async (mode: "skip" | "update") => { if (importErrors.length) return; setSaving(true); try { if (!demoMode) { const response = await fetch("/api/products/bulk-upsert", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode, rows: importRows }) }); if (!response.ok) throw new Error(); } const next = [...products]; for (const row of importRows) { const index = next.findIndex((item) => item.sku === row.sku); if (index >= 0 && mode === "update") next[index] = { ...next[index], ...row, id: next[index].id }; else if (index < 0) next.unshift({ ...row, id: `import-${crypto.randomUUID()}` }); } setProducts(next); setImportOpen(false); toast.success(`${importRows.length} rows imported.`); } catch { toast.error("Import failed before any local changes were applied."); } finally { setSaving(false); } };
  const exportProducts = (format: "csv" | "xlsx") => { const rows = (selected.size ? products.filter((item) => selected.has(item.id)) : filtered).map(toExportRow); const sheet = XLSX.utils.json_to_sheet(rows); if (format === "csv") downloadText(XLSX.utils.sheet_to_csv(sheet), "products.csv", "text/csv;charset=utf-8"); else { const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, "Products"); XLSX.writeFile(book, "products.xlsx"); } toast.success(`${rows.length} products exported.`); };

  return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Stat label="Products" value={String(products.length)} detail="Reusable commerce sources" /><Stat label="Ready to launch" value={String(products.filter((item) => item.readiness >= 80).length)} detail="80%+ brief completion" /><Stat label="Needs attention" value={String(products.filter((item) => item.readiness < 80).length)} detail="Missing product or asset details" /></div>
    <div className="space-y-3 rounded-xl border bg-white p-3"><div className="flex flex-wrap gap-2"><div className="relative min-w-[230px] flex-1"><Search className="absolute left-3 top-2.5 size-4 text-slate-400" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search product, SKU, category or brand" /></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-md border bg-white px-3 text-sm"><option value="all">All statuses</option><option value="active">Active</option><option value="draft">Draft</option><option value="archived">Archived</option></select><Button variant="outline" onClick={() => fileRef.current?.click()}><Upload className="mr-2 size-4" />Import</Button><Button variant="outline" onClick={() => exportProducts("xlsx")}><Download className="mr-2 size-4" />Export</Button><Button variant="outline" onClick={openSheet}><FileSpreadsheet className="mr-2 size-4" />Open in spreadsheet</Button><Button onClick={openNew}><Plus className="mr-2 size-4" />Add new product</Button></div><input ref={fileRef} type="file" className="hidden" accept=".csv,.xlsx,.xls" onChange={parseImport} /><div className="flex flex-wrap items-center gap-2 border-t pt-3"><Button size="sm" variant="ghost" onClick={() => setSelected(new Set(filtered.map((item) => item.id)))}><CheckSquare2 className="mr-1 size-4" />Select filtered</Button><Button size="sm" variant="ghost" disabled={!selected.size} onClick={() => bulk("activate")}>Activate</Button><Button size="sm" variant="ghost" disabled={!selected.size} onClick={() => bulk("archive")}><Archive className="mr-1 size-4" />Archive</Button><Button size="sm" variant="ghost" className="text-rose-600" disabled={!selected.size} onClick={() => bulk("trash")}><Trash2 className="mr-1 size-4" />Trash</Button><span className="text-xs text-slate-500">{selected.size} selected · {filtered.length} shown</span>{demoMode && <Badge className="ml-auto bg-amber-100 text-amber-800">Demo data · saved in this browser</Badge>}</div></div>
    <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs text-slate-500"><tr><th className="p-3"></th><th className="p-3">Product</th><th className="p-3">SKU</th><th className="p-3">Category</th><th className="p-3">Price</th><th className="p-3">Readiness</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{filtered.map((product) => <tr key={product.id} className="border-b last:border-0 hover:bg-slate-50"><td className="p-3"><Checkbox checked={selected.has(product.id)} onCheckedChange={() => setSelected((current) => { const next = new Set(current); next.has(product.id) ? next.delete(product.id) : next.add(product.id); return next; })} /></td><td className="p-3"><div className="flex items-center gap-3"><div className="flex size-12 items-center justify-center overflow-hidden rounded-lg border bg-slate-100">{product.imageUrl ? <img src={product.imageUrl} alt="" className="h-full w-full object-contain" /> : <ImageIcon />}</div><div><p className="font-semibold">{product.name}</p><p className="text-xs text-slate-500">{product.brand || "No brand"}</p></div></div></td><td className="p-3 text-slate-600">{product.sku}</td><td className="p-3 text-slate-600">{product.category}</td><td className="p-3">{formatMoney(product.priceCents, product.currency)}</td><td className="p-3"><Badge className={product.readiness >= 80 ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}>{product.readiness}%</Badge></td><td className="p-3"><span className="capitalize">{product.status}</span></td><td className="p-3"><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => { setDraft(product); setEditorOpen(true); }}>Edit</Button><Button size="sm" onClick={() => createCampaign(product)}><Rocket className="mr-1 size-3.5" />Create campaign</Button></div></td></tr>)}</tbody></table></CardContent></Card>
    <ProductDialog open={editorOpen} onOpenChange={setEditorOpen} draft={draft} setDraft={setDraft} saving={saving} onSave={saveProduct} />
    <SpreadsheetDialog open={sheetOpen} onOpenChange={setSheetOpen} rows={sheetRows} setRows={setSheetRows} saving={saving} onSave={saveSheet} />
    <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Import preview</DialogTitle><DialogDescription>Review validation before any product is written to the catalog.</DialogDescription></DialogHeader>{importErrors.length ? <div className="max-h-52 overflow-auto rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{importErrors.map((error) => <p key={error}>{error}</p>)}</div> : <div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{importRows.length} valid rows are ready. Duplicate SKUs can be skipped or updated.</div>}<div className="max-h-72 overflow-auto rounded border"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-50"><tr><th className="p-2 text-left">Product</th><th className="p-2 text-left">SKU</th><th className="p-2 text-left">Category</th></tr></thead><tbody>{importRows.slice(0, 50).map((row, index) => <tr className="border-t" key={`${row.sku}-${index}`}><td className="p-2">{row.name || <span className="text-rose-600">Missing</span>}</td><td className="p-2">{row.sku || <span className="text-rose-600">Missing</span>}</td><td className="p-2">{row.category}</td></tr>)}</tbody></table></div><DialogFooter><Button variant="outline" onClick={() => commitImport("skip")} disabled={saving || Boolean(importErrors.length)}>Skip duplicates</Button><Button onClick={() => commitImport("update")} disabled={saving || Boolean(importErrors.length)}>Update duplicates</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function ProductDialog({ open, onOpenChange, draft, setDraft, saving, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; draft: CatalogProduct; setDraft: (value: CatalogProduct) => void; saving: boolean; onSave: () => void }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{draft.id ? "Edit product" : "Add new product"}</DialogTitle><DialogDescription>Create one reusable source of truth for campaigns and marketplace assets.</DialogDescription></DialogHeader><div className="grid gap-4 md:grid-cols-2"><Field label="Product name"><Input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="SKU"><Input value={draft.sku} onChange={(event) => setDraft({ ...draft, sku: event.target.value })} /></Field><Field label="Category"><Input value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} /></Field><Field label="Brand"><Input value={draft.brand} onChange={(event) => setDraft({ ...draft, brand: event.target.value })} /></Field><Field label="Price"><Input type="number" value={draft.priceCents / 100} onChange={(event) => setDraft({ ...draft, priceCents: Math.round(Number(event.target.value) * 100) })} /></Field><Field label="Currency"><Input value={draft.currency} maxLength={3} onChange={(event) => setDraft({ ...draft, currency: event.target.value.toUpperCase() })} /></Field><Field label="Image URL"><Input value={draft.imageUrl} onChange={(event) => setDraft({ ...draft, imageUrl: event.target.value })} /></Field><Field label="Promotion"><Input value={draft.promotion} onChange={(event) => setDraft({ ...draft, promotion: event.target.value })} /></Field><Field label="Target market"><Input value={draft.targetMarket} onChange={(event) => setDraft({ ...draft, targetMarket: event.target.value })} /></Field><Field label="Audience"><Input value={draft.audience} onChange={(event) => setDraft({ ...draft, audience: event.target.value })} /></Field><div className="md:col-span-2"><Field label="Description"><Textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></Field></div><Field label="Required claims (comma separated)"><Textarea value={draft.requiredClaims.join(", ")} onChange={(event) => setDraft({ ...draft, requiredClaims: split(event.target.value) })} /></Field><Field label="Forbidden claims (comma separated)"><Textarea value={draft.restrictedClaims.join(", ")} onChange={(event) => setDraft({ ...draft, restrictedClaims: split(event.target.value) })} /></Field></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={saving} onClick={onSave}>{saving ? "Saving…" : "Save product"}</Button></DialogFooter></DialogContent></Dialog>; }
function SpreadsheetDialog({ open, onOpenChange, rows, setRows, saving, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; rows: CatalogProduct[]; setRows: (rows: CatalogProduct[]) => void; saving: boolean; onSave: () => void }) { const update = (index: number, patch: Partial<CatalogProduct>) => setRows(rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row)); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[94vh] max-w-[95vw] overflow-hidden p-0"><DialogHeader className="border-b px-6 py-4"><DialogTitle>Product spreadsheet</DialogTitle><DialogDescription>Edit multiple cells, paste values and save the catalog in one batch.</DialogDescription></DialogHeader><div className="max-h-[70vh] overflow-auto"><table className="min-w-[1200px] text-sm"><thead className="sticky top-0 z-10 bg-slate-100 text-left text-xs"><tr>{["Product name", "SKU", "Category", "Brand", "Price", "Currency", "Market", "Status", "Readiness"].map((label) => <th key={label} className="border-b border-r p-2">{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id || index}>{[["name", row.name], ["sku", row.sku], ["category", row.category], ["brand", row.brand]].map(([key, value]) => <td className="border-b border-r p-1" key={key}><Input className="h-8 min-w-[160px] border-0" value={value as string} onChange={(event) => update(index, { [key]: event.target.value })} /></td>)}<td className="border-b border-r p-1"><Input className="h-8 w-28 border-0" type="number" value={row.priceCents / 100} onChange={(event) => update(index, { priceCents: Math.round(Number(event.target.value) * 100) })} /></td><td className="border-b border-r p-1"><Input className="h-8 w-20 border-0" value={row.currency} onChange={(event) => update(index, { currency: event.target.value.toUpperCase() })} /></td><td className="border-b border-r p-1"><Input className="h-8 min-w-[150px] border-0" value={row.targetMarket} onChange={(event) => update(index, { targetMarket: event.target.value })} /></td><td className="border-b border-r p-1"><select className="h-8 bg-transparent" value={row.status} onChange={(event) => update(index, { status: event.target.value as CatalogProduct["status"] })}><option>draft</option><option>active</option><option>archived</option></select></td><td className="border-b p-1"><Input className="h-8 w-24 border-0" type="number" min={0} max={100} value={row.readiness} onChange={(event) => update(index, { readiness: Number(event.target.value) })} /></td></tr>)}</tbody></table></div><DialogFooter className="border-t p-4"><Button variant="outline" onClick={() => onOpenChange(false)}>Discard</Button><Button disabled={saving} onClick={onSave}>{saving ? "Saving…" : `Save ${rows.length} rows`}</Button></DialogFooter></DialogContent></Dialog>; }
function Stat({ label, value, detail }: { label: string; value: string; detail: string }) { return <Card><CardContent className="p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></CardContent></Card>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label className="text-xs">{label}</Label>{children}</div>; }
function split(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function fromImportRow(row: Record<string, unknown>, index: number): CatalogProduct { const find = (...keys: string[]) => { const match = Object.entries(row).find(([key]) => keys.includes(key.toLowerCase().trim())); return String(match?.[1] ?? "").trim(); }; const price = Number(find("price", "price cents", "price_cents").replace(/[^0-9.]/g, "")) || 0; return { ...emptyProduct, id: `preview-${index}`, name: find("name", "product name", "title"), sku: find("sku", "product sku"), category: find("category") || "Uncategorized", brand: find("brand"), imageUrl: find("image", "image url", "imageurl"), priceCents: Math.round(price * 100), currency: (find("currency") || "USD").slice(0, 3).toUpperCase(), promotion: find("promotion", "promo"), description: find("description"), audience: find("audience", "target customer"), targetMarket: find("market", "target market") || "Vietnam", status: "draft", readiness: 30 }; }
function toExportRow(item: CatalogProduct) { return { "Product name": item.name, SKU: item.sku, Category: item.category, Brand: item.brand, Price: item.priceCents / 100, Currency: item.currency, Promotion: item.promotion, Description: item.description, "Required claims": item.requiredClaims.join(" | "), "Forbidden claims": item.restrictedClaims.join(" | "), Audience: item.audience, Market: item.targetMarket, Status: item.status, Readiness: item.readiness }; }
function downloadText(content: string, name: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
function formatMoney(cents: number, currency: string) { try { return new Intl.NumberFormat("en", { style: "currency", currency }).format(cents / 100); } catch { return `${currency} ${(cents / 100).toFixed(2)}`; } }
function ImageIcon() { return <div className="text-xs text-slate-400">No image</div>; }
